name: carrot-transform.quality
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      - name: run mypy
        run: uv run mypy .
        # run: uv run mypy --check-untyped-defs .
  ruff:
    name: Run Ruff
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run Ruff Checks
        uses: astral-sh/ruff-action@39f75e526a505e26a302f8796977b50c13720edf # v3.2.1
        with:
          args: "check --select I ."
      
      - name: Run Ruff Format
        uses: astral-sh/ruff-action@39f75e526a505e26a302f8796977b50c13720edf # v3.2.1
        with:
          args: "format --check --diff"

  coverage:
    name: carrot-transform coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # run the coverage check, but, don't worry about coverage of the tests themselves
      - name: Run tests
        # run the coverage check, but, don't worry about coverage of the tests themselves
        # ... or the docker tests ...
        run: |
          uv run coverage run --omit=tests/* -m pytest --junitxml=pytest.xml
          uv run coverage xml

      # adds a comment to the PR detailing code coverage
      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: pytest.xml
        continue-on-error: true
