name: Check Code Quality 
 
permissions: 
  contents: read 
 
on:
  push: # always run on push
  pull_request: # always run on pull request

jobs: 
  ruff: 
    name: Run Ruff 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Check out the repo 
        uses: actions/checkout@v4 
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: ruff checks 
        run: | 
          uv run ruff check . --no-fix --output-format=concise 
          uv run ruff format --check . --quiet 
  # TODO; these seem to step on ruff. ideally; we'd run them all (and do changes) then check weitehr anythign was changed
  # isort:
  #   name: Run iSort 
  #   runs-on: ubuntu-latest 
  #   steps: 
  #     - name: Check out the repo 
  #       uses: actions/checkout@v4 
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v5
  #     - name: iSort Checks
  #       run: uv run isort . --check --diff
  # black:
  #   name: Run black
  #   runs-on: ubuntu-latest 
  #   steps: 
  #     - name: Check out the repo 
  #       uses: actions/checkout@v4 
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v5
  #     - name: iSort Checks
  #       run: uv run black . --check
  coverage: 
    name: Check Coverage 
    runs-on: ubuntu-latest 
    permissions: 
      contents: read 
      pull-requests: write 
    steps: 
      - name: Check out the repo 
        uses: actions/checkout@v4 
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run pyTest for Coverage 
        # this will only run once
        run: | 
          uv run coverage run --omit=tests/* -m pytest
          uv run coverage run --omit=tests/* -a -m pytest -m docker
          uv run coverage xml
 
      - name: set pyTest Coverage Comment 
        if: github.event_name == 'pull_request' 
        uses: MishaKav/pytest-coverage-comment@main 
        with: 
          pytest-xml-coverage-path: coverage.xml 
          junitxml-path: pytest.xml 
        continue-on-error: true 
 
