name: Check Code Quality 
 
permissions: 
  contents: read 
 
on:
  pull_request: # always run on pull request

jobs: 
  coverage: 
    name: Check Coverage 
    runs-on: ubuntu-latest 
    permissions: 
      contents: read 
      pull-requests: write 
    steps: 
      - name: Check out the repo 
        uses: actions/checkout@v4 
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run pyTest for Coverage 
        # this will only run once
        run: | 
          uv run coverage run --omit=tests/* -m pytest
          uv run coverage run --omit=tests/* -a -m pytest -m docker
          uv run coverage xml
 
      - name: set pyTest Coverage Comment 
        if: github.event_name == 'pull_request' 
        uses: MishaKav/pytest-coverage-comment@main 
        with: 
          pytest-xml-coverage-path: coverage.xml 
          junitxml-path: pytest.xml 
        continue-on-error: true 
 
