name: Upload Python Package

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["Run Pytest with uv"]  # Must match exactly the name of test workflow
    types:
      - completed
    branches:
      - main # tag in main branch

jobs:
  publish-to-pypi-test:
    name: Publish to PyPI test
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: testpypi
      url: https://test.pypi.org/p/carrot-transform
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    # - name: Publish distribution 📦 to TestPyPI
    #   # we publish to test whenever there's a commit to main
    #   # if: github.ref == 'refs/heads/main'
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     repository-url: https://test.pypi.org/legacy/

  publish-to-pypi-main:
    name: Publish to PyPI main
    needs: [publish-to-pypi-test]
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_sha, 'refs/tags/v') }}
    environment:
      name: pypi
      url: https://pypi.org/p/carrot-transform
    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
        
      # - name: Publish distribution 📦 to PyPI
      #   # we publish to main whever there's a version with a tag
      #   if: startsWith(github.ref, 'refs/tags/v') 
      #   uses: pypa/gh-action-pypi-publish@release/v1