name: carrot-transform-pytest
###
# most of this is copied into the publish file
##
permissions:
  contents: read
  pull-requests: write

on:
  push: # always run on push
  pull_request: # always run on pull request

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          uv run pytest
  coverage:
    name: set coverage comment
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run tests
        # run the coverage check, but, don't worry about coverage of the tests themselves
        run: |
          uv run coverage run --omit=tests/* -m pytest --junitxml=pytest.xml
          uv run coverage xml

      # adds a comment to the PR detailing code coverage
      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: pytest.xml
        continue-on-error: true
  ruff:
    name: ruff checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: ruff checks
        run: |
          uv run ruff check . --no-fix --output-format=concise
          uv run ruff format --check . --quiet
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build package
        run: |
          rm -rf dist/ build/
          uv run python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
