name: carrot-transform-pytest
###
# most of this is copied into the publish file
##
permissions:
  contents: read
  pull-requests: write

on:
  push: # always run on push
  pull_request: # always run on pull request

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python
        run: uv python install

      - name: Run tests
        run: |
          uv run pytest --junitxml=pytest.xml
          uv run coverage run -m pytest
          uv run coverage xml

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: pytest.xml
        continue-on-error: true

      - name: ruff checks
        run: |
          ruff check . --no-fix --output-format=concise
          ruff format --check . --quiet

  docker_tests:
    name: Docker Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Run tests (docker)
        run: uv run pytest -m docker

  build:
    name: Build distribution
    runs-on: ubuntu-latest
    needs:
      - test
      - docker_tests
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Build package
        run: |
          rm -rf dist/ build/
          uv run python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
