name: Run Pytest with uv

permissions:
  contents: read

on:
  push: # always run on push
  pull_request: # just always run on pull request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python
        run: uv python install

      - name: Run tests
        run: uv run pytest
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    needs: 
      - test
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        
      - name: Set up Python
        run: uv python install

      - name: Build package
        run: |
          rm -rf dist/ build/
          uv run python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
